- hosts: kubeall
  environment:
    LC_ALL: C
    LANG: C

  tasks:

  - name: install python
    raw: test -e /usr/bin/python || (apt -qqy update && apt install -y python)
    register: output
    changed_when: output.stdout != ""
